"""
https://projecteuler.net/problem=44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""

limite = 10**4

nbPentagonaux = [i*(3*i+1) / 2 for i in range(1,limite+1)]
print(nbPentagonaux[-1])
diffMin = float("inf")

def recherche(cible):
    inf = 0
    sup = len(nbPentagonaux) - 1

    while inf <= sup:
        moitie = (inf + sup)//2
        if nbPentagonaux[moitie] == cible:
            return True 
        elif nbPentagonaux[moitie] < cible:
            inf = moitie + 1 
        else:
            sup = moitie - 1

    return False 

for i in range(limite):
    if not i % 1000: print(i)
    for a in range(i+1, limite):
        if recherche(nbPentagonaux[i] + nbPentagonaux[a]) and recherche(nbPentagonaux[a] - nbPentagonaux[i]):
            diffMin = min(diffMin, nbPentagonaux[a] - nbPentagonaux[i] )

print(diffMin)